# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e606bd48b1987039c44300baee33648e309227bc5e2b521436aebd20a1f2fb7a28a8644455f3622047710d358a461e43ca4b0bc1de57a02652f32cbf31c1d79

test:
  secret_key_base: 06a2151cc60ce69bc0bacda2d89e12a477c550d98bf47c9432831efa1f397fec0b6efa4f3e1415a686d2e96332ffa2566186da3047fd027a276bebc910e48cfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
